### ISSUE TITLE
Penambahan cek id

### ISSUE THREAD

**Issue by Odding07** [ihsangan/valid#2]
Bisakah melakukan cek id Clash Of Clans atau Pubg Mobile?

**Comment by ihsangan** [comment]
Untuk Coc bisa tapi sayang saya kekurangan waktu untuk menambahkannya, untuk pugm sayangnya tidak bisa

**Comment by Richeese4** [comment]
Hallo bg ditungggu next update berbagai game:)

**Comment by prastius** [comment]
Halo bang, untuk deteksi form bodynya mungkin ada caranya bang seperti voucherPricePoint.id, voucherPricePoint.price, etc? jadi bisa kami bantu untuk kembangin cek id game yang lain

**Comment by ihsangan** [comment]
Clash Of Clans sudah ditambahkan, silakan lihat [disini](https://github.com/ihsangan/valid?tab=readme-ov-file#clash-of-clans).
