### ISSUE TITLE
Mendapatkan 'RESULT_CODE: 237'

### ISSUE THREAD

**Issue by TwoKnightRabbits** [ihsangan/valid#5]
Saya mendapatkan "RESULT_CODE 237" setelah melakukan POST. Kalau tidak salah kemarin saya sempat coba itu mendapatkan hasilnya, namun saat ini mendapatkan hasil code 237

- **Hasil untuk hari ini :**
<img width="632" alt="image" src="https://github.com/ihsangan/valid/assets/124092534/e9a9a7b7-dda3-48a3-b7b4-11a55439c41f">

- **URL :**
<img width="618" alt="image" src="https://github.com/ihsangan/valid/assets/124092534/289235a7-aaa6-4e35-a010-a4a5f5a28a69">

- **Isi Body :**
<img width="618" alt="image" src="https://github.com/ihsangan/valid/assets/124092534/8e2c5cce-73fc-445b-85f7-a0db5a820c6b">

- **Output Code :**
<img width="632" alt="image" src="https://github.com/ihsangan/valid/assets/124092534/d7b51537-9072-44d5-98e5-d0120400263a">

Seperti ada kendala di API dari codashopnya.

Itu saja yang saya dapatkan, mungkin ada jalannya. Terimma kasih

**Comment by ihsangan** [comment]
Ini juga sudah saya notis kemarin, silahkan liat commit saya 3c02144, alasannya produk id sebelumnya dihapus dan sekarang harus pakai value yang baru
